name: Build Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  Qt_minor_version: 5.15
  Qt_patch_version: 5.15.15
  openssl_location: C:\Program Files\OpenSSL
  sevenzip_location: C:\Program Files\7-Zip
  BUILD_TYPE: Release
  
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Download Qt ${{ env.Qt_patch_version }}
        shell: pwsh
        run: |
          $AllProtocols = [System.Net.SecurityProtocolType]'Tls,Tls11,Tls12'
          [System.Net.ServicePointManager]::SecurityProtocol = $AllProtocols
          
          $ProgressPreference = 'SilentlyContinue'
          $qt_archive_file = "C:\" + "qt-everywhere-opensource-src-${{ env.Qt_patch_version }}" + ".tar.xz"
          Invoke-WebRequest -Uri https://download.qt.io/archive/qt/${{ env.Qt_minor_version }}/${{ env.Qt_patch_version }}/single/qt-everywhere-opensource-src-${{ env.Qt_patch_version }}.tar.xz -OutFile $qt_archive_file
          
      - name: Extract Qt ${{ env.Qt_patch_version }}
        working-directory: ${{ env.sevenzip_location }}
        shell: cmd
        run: |
          7z x C:\qt-everywhere-opensource-src-${{ env.Qt_patch_version }}.tar.xz -oC:\
          7z x C:\qt-everywhere-opensource-src-${{ env.Qt_patch_version }}.tar -oC:\
          del C:\qt-everywhere-opensource-src-${{ env.Qt_patch_version }}.tar.xz
          del C:\qt-everywhere-opensource-src-${{ env.Qt_patch_version }}.tar
          
      - name: Install Ninja
        shell: pwsh
        run: |
          choco install ninja

      - name: Configure Qt ${{ env.Qt_patch_version }}
        working-directory: C:/qt-everywhere-src-${{ env.Qt_patch_version }}
        shell: cmd
        run: |
          configure.bat ^
          -opensource ^
          -confirm-license ^
          -release ^
          -static ^
          -static-runtime ^
          -platform win32-msvc ^
          -mp ^
          -nomake examples ^
          -nomake tests ^
          -no-compile-examples ^
          -no-dbus ^
          -no-accessibility ^
          -qt-doubleconversion ^
          -no-icu ^
          -openssl-linked OPENSSL_LIBS="-lUser32 -lAdvapi32 -lGdi32 -lCrypt32 -lWs2_32" OPENSSL_PREFIX="${{ env.openssl_location }}" OPENSSL_LIBS_RELEASE="-llibcrypto64MT -llibssl64MT" OPENSSL_LIBS_DEBUG="-llibcrypto64MTd -llibssl64MTd" ^
          -I "${{ env.openssl_location }}\include" ^
          -L "${{ env.openssl_location }}\lib\VC\static" ^
          -L "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Lib" ^
          -no-schannel ^
          -no-securetransport ^
          -no-cups ^
          -no-fontconfig ^
          -no-freetype ^
          -no-harfbuzz ^
          -no-gtk ^
          -no-opengl ^
          -no-direct2d ^
          -no-eglfs ^
          -no-ico ^
          -no-sql-db2 ^
          -no-sql-ibase ^
          -no-sql-mysql ^
          -no-sql-oci ^
          -no-sql-odbc ^
          -no-sql-psql ^
          -no-sql-sqlite ^
          -no-sql-sqlite2 ^
          -no-sql-tds ^
          -no-tiff ^
          -no-webp ^
          -no-feature-sqlmodel ^
          -no-feature-testlib_selfcover ^
          -no-feature-textmarkdownreader ^
          -no-feature-textmarkdownwriter ^
          -no-feature-textodfwriter ^
          -skip qt3d ^
          -skip qtactiveqt ^
          -skip qtandroidextras ^
          -skip qtcanvas3d ^
          -skip qtcharts ^
          -skip qtconnectivity ^
          -skip qtdatavis3d ^
          -skip qtdeclarative ^
          -skip qtdoc ^
          -skip qtfeedback ^
          -skip qtgamepad ^
          -skip qtgraphicaleffects ^
          -skip qtlocation ^
          -skip qtlottie ^
          -skip qtmacextras ^
          -skip qtmultimedia ^
          -skip qtnetworkauth ^
          -skip qtpim ^
          -skip qtpurchasing ^
          -skip qtqa ^
          -skip qtquick3d ^
          -skip qtquickcontrols ^
          -skip qtquickcontrols2 ^
          -skip qtquicktimeline ^
          -skip qtremoteobjects ^
          -skip qtrepotools ^
          -skip qtscript ^
          -skip qtscxml ^
          -skip qtsensors ^
          -skip qtserialbus ^
          -skip qtserialport ^
          -skip qtspeech ^
          -skip qtsystems ^
          -skip qttools ^
          -skip qttranslations ^
          -skip qtwayland ^
          -skip qtwebchannel ^
          -skip qtwebengine ^
          -skip qtwebglplugin ^
          -skip qtwebsockets ^
          -skip qtwebview ^
          -skip qtwinextras ^
          -skip qtx11extras ^
          -skip qtxmlpatterns

      - name: Build Qt ${{ env.Qt_patch_version }}
        working-directory: C:/qt-everywhere-src-${{ env.Qt_patch_version }}
        shell: pwsh
        run: |
          nmake
          
      - name: Install Qt ${{ env.Qt_patch_version }}
        working-directory: C:/qt-everywhere-src-${{ env.Qt_patch_version }}
        shell: pwsh
        run: |
          nmake install
          
      - uses: actions/checkout@v4
      - name: Build project
        run: cmake -S . -B build -G "Ninja Multi-Config" && cmake --build build --config ${{ env.BUILD_TYPE }}
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-artifact
          path: build/${{ env.BUILD_TYPE }}
          if-no-files-found: ignore
          retention-days: 0
