name: Build Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  openssl_location: C:\Program Files\OpenSSL
  sevenzip_location: C:\Program Files\7-Zip
  
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check OpenSSL
        working-directory: ${{ env.openssl_location }}
        run: |
          dir
          dir bin
          dir include
          dir lib
# - uses: ilammy/msvc-dev-cmd@v1
